version: '3.9'
services:
  app:
    image: node:latest
    volumes:
      - ./playground:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm run dev
  # db:
  #   image: surrealdb/surrealdb:latest
  #   ports:
  #     - "8000:8000"
  #   command: start --user root --pass root file://database
  #   volumes:
  #     - ./data/database.db:/database.db